<?php

/**
 * This file was generated by phpSPO model generator 2019-10-12T20:10:10+00:00 16.0.19402.12016
 */
namespace Office365\SharePoint\Translation;

use Office365\Runtime\ClientValue;

class TranslationItemInfo extends ClientValue
{
    /**
     * @var bool
     */
    public $Canceled;
    /**
     * @var string
     */
    public $ErrorMessage;
    /**
     * @var bool
     */
    public $Failed;
    /**
     * @var bool
     */
    public $InProgress;
    /**
     * @var string
     */
    public $InputFile;
    /**
     * @var bool
     */
    public $NotStarted;
    /**
     * @var string
     */
    public $OutputFile;
    /**
     * @var integer
     */
    public $Result;
    /**
     * @var bool
     */
    public $Succeeded;
    /**
     * @var string
     */
    public $TranslationId;
}