<?php

/**
 * This file was generated by phpSPO model generator 2020-05-13T12:20:55+00:00 16.0.20029.12010
 */
namespace Office365\SharePoint\Publishing\PortalLaunch;

use Office365\Runtime\ClientValue;
class PortalLaunchWave extends ClientValue
{
    /**
     * @var string
     */
    public $LaunchDateUtc;
    /**
     * @var string
     */
    public $Name;
    /**
     * @var integer
     */
    public $Order;
}