<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:10:14+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValue;
class AndroidMinimumOperatingSystem extends ClientValue
{
    /**
     * @var bool
     */
    public $V4_0;
    /**
     * @var bool
     */
    public $V4_0_3;
    /**
     * @var bool
     */
    public $V4_1;
    /**
     * @var bool
     */
    public $V4_2;
    /**
     * @var bool
     */
    public $V4_3;
    /**
     * @var bool
     */
    public $V4_4;
    /**
     * @var bool
     */
    public $V5_0;
    /**
     * @var bool
     */
    public $V5_1;
}