<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:10:14+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValue;
class AppListItem extends ClientValue
{
    /**
     * @var string
     */
    public $Name;
    /**
     * @var string
     */
    public $Publisher;
    /**
     * @var string
     */
    public $AppStoreUrl;
    /**
     * @var string
     */
    public $AppId;
}