<?php

/**
 * Generated by phpSPO model generator 2020-05-24T21:39:44+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValueObject;
class AppliedConditionalAccessPolicy extends ClientValueObject
{
    /**
     * @var string
     */
    public $Id;
    /**
     * @var string
     */
    public $DisplayName;
    /**
     * @var array
     */
    public $EnforcedGrantControls;
    /**
     * @var array
     */
    public $EnforcedSessionControls;
}