<?php

/**
 * Generated by phpSPO model generator 2020-05-24T21:52:14+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValueObject;
class AssignedLicense extends ClientValueObject
{
    /**
     * @var array
     */
    public $DisabledPlans;
    /**
     * @var string
     */
    public $SkuId;
}