<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:10:14+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientObject;
use Office365\Runtime\ResourcePath;
class DeviceEnrollmentWindowsHelloForBusinessConfiguration extends ClientObject
{
    /**
     * @return integer
     */
    public function getPinMinimumLength()
    {
        if (!$this->isPropertyAvailable("PinMinimumLength")) {
            return null;
        }
        return $this->getProperty("PinMinimumLength");
    }
    /**
     * @var integer
     */
    public function setPinMinimumLength($value)
    {
        $this->setProperty("PinMinimumLength", $value, true);
    }
    /**
     * @return integer
     */
    public function getPinMaximumLength()
    {
        if (!$this->isPropertyAvailable("PinMaximumLength")) {
            return null;
        }
        return $this->getProperty("PinMaximumLength");
    }
    /**
     * @var integer
     */
    public function setPinMaximumLength($value)
    {
        $this->setProperty("PinMaximumLength", $value, true);
    }
    /**
     * @return bool
     */
    public function getSecurityDeviceRequired()
    {
        if (!$this->isPropertyAvailable("SecurityDeviceRequired")) {
            return null;
        }
        return $this->getProperty("SecurityDeviceRequired");
    }
    /**
     * @var bool
     */
    public function setSecurityDeviceRequired($value)
    {
        $this->setProperty("SecurityDeviceRequired", $value, true);
    }
    /**
     * @return bool
     */
    public function getUnlockWithBiometricsEnabled()
    {
        if (!$this->isPropertyAvailable("UnlockWithBiometricsEnabled")) {
            return null;
        }
        return $this->getProperty("UnlockWithBiometricsEnabled");
    }
    /**
     * @var bool
     */
    public function setUnlockWithBiometricsEnabled($value)
    {
        $this->setProperty("UnlockWithBiometricsEnabled", $value, true);
    }
    /**
     * @return bool
     */
    public function getRemotePassportEnabled()
    {
        if (!$this->isPropertyAvailable("RemotePassportEnabled")) {
            return null;
        }
        return $this->getProperty("RemotePassportEnabled");
    }
    /**
     * @var bool
     */
    public function setRemotePassportEnabled($value)
    {
        $this->setProperty("RemotePassportEnabled", $value, true);
    }
    /**
     * @return integer
     */
    public function getPinPreviousBlockCount()
    {
        if (!$this->isPropertyAvailable("PinPreviousBlockCount")) {
            return null;
        }
        return $this->getProperty("PinPreviousBlockCount");
    }
    /**
     * @var integer
     */
    public function setPinPreviousBlockCount($value)
    {
        $this->setProperty("PinPreviousBlockCount", $value, true);
    }
    /**
     * @return integer
     */
    public function getPinExpirationInDays()
    {
        if (!$this->isPropertyAvailable("PinExpirationInDays")) {
            return null;
        }
        return $this->getProperty("PinExpirationInDays");
    }
    /**
     * @var integer
     */
    public function setPinExpirationInDays($value)
    {
        $this->setProperty("PinExpirationInDays", $value, true);
    }
}