<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:10:14+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValueObject;
class Diagnostic extends ClientValueObject
{
    /**
     * @var string
     */
    public $Message;
    /**
     * @var string
     */
    public $Url;
}