<?php

/**
 * Generated by phpSPO model generator 2020-05-24T21:52:14+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientObject;
use Office365\Runtime\ResourcePath;
/**
 * Represents an Azure Active Directory object. The **directoryObject** type is the base type for many other directory entity types.
 */
class DirectoryObject extends ClientObject
{
}