<?php

/**
 * Generated by phpSPO model generator 2020-05-24T22:08:35+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientObject;
use Office365\Runtime\ResourcePath;
/**
 *  "The drive resource is the top level object representing a user's OneDrive or a document library in SharePoint."
 */
class Drive extends ClientObject
{
    /**
     * @return string
     */
    public function getDriveType()
    {
        if (!$this->isPropertyAvailable("DriveType")) {
            return null;
        }
        return $this->getProperty("DriveType");
    }
    /**
     * @var string
     */
    public function setDriveType($value)
    {
        $this->setProperty("DriveType", $value, true);
    }
}