<?php

/**
 * Generated by phpSPO model generator 2020-05-29T07:19:37+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientObject;
use Office365\Runtime\ResourcePath;
class Endpoint extends ClientObject
{
    /**
     * @return string
     */
    public function getCapability()
    {
        if (!$this->isPropertyAvailable("Capability")) {
            return null;
        }
        return $this->getProperty("Capability");
    }
    /**
     * @var string
     */
    public function setCapability($value)
    {
        $this->setProperty("Capability", $value, true);
    }
    /**
     * @return string
     */
    public function getProviderId()
    {
        if (!$this->isPropertyAvailable("ProviderId")) {
            return null;
        }
        return $this->getProperty("ProviderId");
    }
    /**
     * @var string
     */
    public function setProviderId($value)
    {
        $this->setProperty("ProviderId", $value, true);
    }
    /**
     * @return string
     */
    public function getProviderName()
    {
        if (!$this->isPropertyAvailable("ProviderName")) {
            return null;
        }
        return $this->getProperty("ProviderName");
    }
    /**
     * @var string
     */
    public function setProviderName($value)
    {
        $this->setProperty("ProviderName", $value, true);
    }
    /**
     * @return string
     */
    public function getUri()
    {
        if (!$this->isPropertyAvailable("Uri")) {
            return null;
        }
        return $this->getProperty("Uri");
    }
    /**
     * @var string
     */
    public function setUri($value)
    {
        $this->setProperty("Uri", $value, true);
    }
    /**
     * @return string
     */
    public function getProviderResourceId()
    {
        if (!$this->isPropertyAvailable("ProviderResourceId")) {
            return null;
        }
        return $this->getProperty("ProviderResourceId");
    }
    /**
     * @var string
     */
    public function setProviderResourceId($value)
    {
        $this->setProperty("ProviderResourceId", $value, true);
    }
}