<?php

/**
 * Generated by phpSPO model generator 2020-05-25T06:42:59+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValueObject;
class Folder extends ClientValueObject
{
    /**
     * @var integer
     */
    public $ChildCount;
    /**
     * @var FolderView
     */
    public $View;
}