<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:07:25+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValue;
class GroupAssignmentTarget extends ClientValue
{
    /**
     * @var string
     */
    public $GroupId;
}