<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:10:14+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientObject;
use Office365\Runtime\ResourcePath;
class IosMobileAppConfiguration extends ClientObject
{
    /**
     * @return string
     */
    public function getEncodedSettingXml()
    {
        if (!$this->isPropertyAvailable("EncodedSettingXml")) {
            return null;
        }
        return $this->getProperty("EncodedSettingXml");
    }
    /**
     * @var string
     */
    public function setEncodedSettingXml($value)
    {
        $this->setProperty("EncodedSettingXml", $value, true);
    }
}