<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:10:14+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValue;
class IosMinimumOperatingSystem extends ClientValue
{
    /**
     * @var bool
     */
    public $V8_0;
    /**
     * @var bool
     */
    public $V9_0;
    /**
     * @var bool
     */
    public $V10_0;
    /**
     * @var bool
     */
    public $V11_0;
    /**
     * @var bool
     */
    public $V12_0;
    /**
     * @var bool
     */
    public $V13_0;
}