<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:10:14+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValueObject;
class IPv6Range extends ClientValueObject
{
    /**
     * @var string
     */
    public $LowerAddress;
    /**
     * @var string
     */
    public $UpperAddress;
}