<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:10:14+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientObject;
use Office365\Runtime\ResourcePath;
class ManagedAppStatusRaw extends ClientObject
{
    /**
     * @return Json
     */
    public function getContent()
    {
        if (!$this->isPropertyAvailable("Content")) {
            return null;
        }
        return $this->getProperty("Content");
    }
    /**
     * @var Json
     */
    public function setContent($value)
    {
        $this->setProperty("Content", $value, true);
    }
}