<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:07:25+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValueObject;
class NumberColumn extends ClientValueObject
{
    /**
     * @var string
     */
    public $DecimalPlaces;
    /**
     * @var string
     */
    public $DisplayAs;
    /**
     * @var double
     */
    public $Maximum;
    /**
     * @var double
     */
    public $Minimum;
}