<?php

/**
 * Generated by phpSPO model generator 2020-05-24T22:02:06+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValue;
class OnPremisesProvisioningError extends ClientValue
{
    /**
     * @var string
     */
    public $Value;
    /**
     * @var string
     */
    public $Category;
    /**
     * @var string
     */
    public $PropertyCausingError;
}