<?php

/**
 * Generated by phpSPO model generator 2020-05-24T22:08:35+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValueObject;
class Phone extends ClientValueObject
{
    /**
     * @var string
     */
    public $Number;
    /**
     * @var string
     */
    public $Region;
    /**
     * @var string
     */
    public $Language;
}