<?php

/**
 * Generated by phpSPO model generator 2020-05-24T22:08:35+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValueObject;
class PhysicalOfficeAddress extends ClientValueObject
{
    /**
     * @var string
     */
    public $City;
    /**
     * @var string
     */
    public $CountryOrRegion;
    /**
     * @var string
     */
    public $OfficeLocation;
    /**
     * @var string
     */
    public $PostalCode;
    /**
     * @var string
     */
    public $State;
    /**
     * @var string
     */
    public $Street;
}