<?php

/**
 * Generated by phpSPO model generator 2020-05-29T07:19:37+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientObject;
use Office365\Runtime\ResourcePath;
/**
 *  "Represents a place. This is the base type for a room or roomList."
 */
class Place extends ClientObject
{
    /**
     * @return string
     */
    public function getDisplayName()
    {
        if (!$this->isPropertyAvailable("DisplayName")) {
            return null;
        }
        return $this->getProperty("DisplayName");
    }
    /**
     * @var string
     */
    public function setDisplayName($value)
    {
        $this->setProperty("DisplayName", $value, true);
    }
    /**
     * @return string
     */
    public function getPhone()
    {
        if (!$this->isPropertyAvailable("Phone")) {
            return null;
        }
        return $this->getProperty("Phone");
    }
    /**
     * @var string
     */
    public function setPhone($value)
    {
        $this->setProperty("Phone", $value, true);
    }
}