<?php

/**
 * Generated by phpSPO model generator 2020-05-29T07:19:37+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValueObject;
class PublicErrorDetail extends ClientValueObject
{
    /**
     * @var string
     */
    public $Code;
    /**
     * @var string
     */
    public $Message;
    /**
     * @var string
     */
    public $Target;
}