<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:12:31+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValueObject;
class RecentNotebook extends ClientValueObject
{
    /**
     * @var string
     */
    public $DisplayName;
    /**
     * @var RecentNotebookLinks
     */
    public $Links;
}