<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:10:14+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValue;
class RgbColor extends ClientValue
{
    /**
     * @var string
     */
    public $R;
    /**
     * @var string
     */
    public $G;
    /**
     * @var string
     */
    public $B;
}