<?php

/**
 * Generated by phpSPO model generator 2020-05-24T22:10:26+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValueObject;
class SharepointIds extends ClientValueObject
{
    /**
     * @var string
     */
    public $ListId;
    /**
     * @var string
     */
    public $ListItemId;
    /**
     * @var string
     */
    public $ListItemUniqueId;
    /**
     * @var string
     */
    public $SiteId;
    /**
     * @var string
     */
    public $SiteUrl;
    /**
     * @var string
     */
    public $WebId;
}