<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:07:25+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValueObject;
class SharingLink extends ClientValueObject
{
    /**
     * @var Identity
     */
    public $Application;
    /**
     * @var string
     */
    public $Scope;
    /**
     * @var string
     */
    public $Type;
    /**
     * @var string
     */
    public $WebUrl;
}