<?php

/**
 * Generated by phpSPO model generator 2020-05-29T07:19:37+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientObject;
use Office365\Runtime\ResourcePath;
/**
 * Represents a unit of scheduled work in a [schedule](schedule.md). 
 */
class Shift extends ClientObject
{
    /**
     * @return string
     */
    public function getUserId()
    {
        if (!$this->isPropertyAvailable("UserId")) {
            return null;
        }
        return $this->getProperty("UserId");
    }
    /**
     * @var string
     */
    public function setUserId($value)
    {
        $this->setProperty("UserId", $value, true);
    }
    /**
     * @return string
     */
    public function getSchedulingGroupId()
    {
        if (!$this->isPropertyAvailable("SchedulingGroupId")) {
            return null;
        }
        return $this->getProperty("SchedulingGroupId");
    }
    /**
     * @var string
     */
    public function setSchedulingGroupId($value)
    {
        $this->setProperty("SchedulingGroupId", $value, true);
    }
}