<?php

/**
 * Generated by phpSPO model generator 2020-05-29T07:19:37+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValueObject;
class SiteCollection extends ClientValueObject
{
    /**
     * @var string
     */
    public $Hostname;
    /**
     * @var Root
     */
    public $Root;
    /**
     * @var string
     */
    public $DataLocationCode;
}