<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:10:14+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValue;
class TeamGuestSettings extends ClientValue
{
    /**
     * @var bool
     */
    public $AllowCreateUpdateChannels;
    /**
     * @var bool
     */
    public $AllowDeleteChannels;
}