<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:10:14+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValueObject;
class TeamMessagingSettings extends ClientValueObject
{
    /**
     * @var bool
     */
    public $AllowUserEditMessages;
    /**
     * @var bool
     */
    public $AllowUserDeleteMessages;
    /**
     * @var bool
     */
    public $AllowOwnerDeleteMessages;
    /**
     * @var bool
     */
    public $AllowTeamMentions;
    /**
     * @var bool
     */
    public $AllowChannelMentions;
}