<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:10:14+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValue;
class TeamFunSettings extends ClientValue
{
    /**
     * @var bool
     */
    public $AllowGiphy;
    /**
     * @var bool
     */
    public $AllowStickersAndMemes;
    /**
     * @var bool
     */
    public $AllowCustomMemes;
}