<?php

/**
 * Generated by phpSPO model generator 2020-05-29T07:19:37+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientObject;
use Office365\Runtime\ResourcePath;
class TermsAndConditionsAcceptanceStatus extends ClientObject
{
    /**
     * @return string
     */
    public function getUserDisplayName()
    {
        if (!$this->isPropertyAvailable("UserDisplayName")) {
            return null;
        }
        return $this->getProperty("UserDisplayName");
    }
    /**
     * @var string
     */
    public function setUserDisplayName($value)
    {
        $this->setProperty("UserDisplayName", $value, true);
    }
    /**
     * @return integer
     */
    public function getAcceptedVersion()
    {
        if (!$this->isPropertyAvailable("AcceptedVersion")) {
            return null;
        }
        return $this->getProperty("AcceptedVersion");
    }
    /**
     * @var integer
     */
    public function setAcceptedVersion($value)
    {
        $this->setProperty("AcceptedVersion", $value, true);
    }
    /**
     * @return TermsAndConditions
     */
    public function getTermsAndConditions()
    {
        if (!$this->isPropertyAvailable("TermsAndConditions")) {
            $this->setProperty("TermsAndConditions", new TermsAndConditions($this->getContext(), new ResourcePath("TermsAndConditions", $this->getResourcePath())));
        }
        return $this->getProperty("TermsAndConditions");
    }
    /**
     * @return string
     */
    public function getUserPrincipalName()
    {
        if (!$this->isPropertyAvailable("UserPrincipalName")) {
            return null;
        }
        return $this->getProperty("UserPrincipalName");
    }
    /**
     * @var string
     */
    public function setUserPrincipalName($value)
    {
        $this->setProperty("UserPrincipalName", $value, true);
    }
}