<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:12:31+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValueObject;
class UpdateWindowsDeviceAccountActionParameter extends ClientValueObject
{
    /**
     * @var bool
     */
    public $PasswordRotationEnabled;
    /**
     * @var bool
     */
    public $CalendarSyncEnabled;
    /**
     * @var string
     */
    public $DeviceAccountEmail;
    /**
     * @var string
     */
    public $ExchangeServer;
    /**
     * @var string
     */
    public $SessionInitiationProtocalAddress;
    /**
     * @var WindowsDeviceAccount
     */
    public $DeviceAccount;
}