<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:10:14+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValue;
class WindowsMinimumOperatingSystem extends ClientValue
{
    /**
     * @var bool
     */
    public $V8_0;
    /**
     * @var bool
     */
    public $V8_1;
    /**
     * @var bool
     */
    public $V10_0;
}