<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:10:14+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientObject;
use Office365\Runtime\ResourcePath;
class Windows10TeamGeneralConfiguration extends ClientObject
{
    /**
     * @return bool
     */
    public function getAzureOperationalInsightsBlockTelemetry()
    {
        if (!$this->isPropertyAvailable("AzureOperationalInsightsBlockTelemetry")) {
            return null;
        }
        return $this->getProperty("AzureOperationalInsightsBlockTelemetry");
    }
    /**
     * @var bool
     */
    public function setAzureOperationalInsightsBlockTelemetry($value)
    {
        $this->setProperty("AzureOperationalInsightsBlockTelemetry", $value, true);
    }
    /**
     * @return string
     */
    public function getAzureOperationalInsightsWorkspaceId()
    {
        if (!$this->isPropertyAvailable("AzureOperationalInsightsWorkspaceId")) {
            return null;
        }
        return $this->getProperty("AzureOperationalInsightsWorkspaceId");
    }
    /**
     * @var string
     */
    public function setAzureOperationalInsightsWorkspaceId($value)
    {
        $this->setProperty("AzureOperationalInsightsWorkspaceId", $value, true);
    }
    /**
     * @return string
     */
    public function getAzureOperationalInsightsWorkspaceKey()
    {
        if (!$this->isPropertyAvailable("AzureOperationalInsightsWorkspaceKey")) {
            return null;
        }
        return $this->getProperty("AzureOperationalInsightsWorkspaceKey");
    }
    /**
     * @var string
     */
    public function setAzureOperationalInsightsWorkspaceKey($value)
    {
        $this->setProperty("AzureOperationalInsightsWorkspaceKey", $value, true);
    }
    /**
     * @return bool
     */
    public function getConnectAppBlockAutoLaunch()
    {
        if (!$this->isPropertyAvailable("ConnectAppBlockAutoLaunch")) {
            return null;
        }
        return $this->getProperty("ConnectAppBlockAutoLaunch");
    }
    /**
     * @var bool
     */
    public function setConnectAppBlockAutoLaunch($value)
    {
        $this->setProperty("ConnectAppBlockAutoLaunch", $value, true);
    }
    /**
     * @return bool
     */
    public function getMaintenanceWindowBlocked()
    {
        if (!$this->isPropertyAvailable("MaintenanceWindowBlocked")) {
            return null;
        }
        return $this->getProperty("MaintenanceWindowBlocked");
    }
    /**
     * @var bool
     */
    public function setMaintenanceWindowBlocked($value)
    {
        $this->setProperty("MaintenanceWindowBlocked", $value, true);
    }
    /**
     * @return integer
     */
    public function getMaintenanceWindowDurationInHours()
    {
        if (!$this->isPropertyAvailable("MaintenanceWindowDurationInHours")) {
            return null;
        }
        return $this->getProperty("MaintenanceWindowDurationInHours");
    }
    /**
     * @var integer
     */
    public function setMaintenanceWindowDurationInHours($value)
    {
        $this->setProperty("MaintenanceWindowDurationInHours", $value, true);
    }
    /**
     * @return bool
     */
    public function getMiracastBlocked()
    {
        if (!$this->isPropertyAvailable("MiracastBlocked")) {
            return null;
        }
        return $this->getProperty("MiracastBlocked");
    }
    /**
     * @var bool
     */
    public function setMiracastBlocked($value)
    {
        $this->setProperty("MiracastBlocked", $value, true);
    }
    /**
     * @return bool
     */
    public function getMiracastRequirePin()
    {
        if (!$this->isPropertyAvailable("MiracastRequirePin")) {
            return null;
        }
        return $this->getProperty("MiracastRequirePin");
    }
    /**
     * @var bool
     */
    public function setMiracastRequirePin($value)
    {
        $this->setProperty("MiracastRequirePin", $value, true);
    }
    /**
     * @return bool
     */
    public function getSettingsBlockMyMeetingsAndFiles()
    {
        if (!$this->isPropertyAvailable("SettingsBlockMyMeetingsAndFiles")) {
            return null;
        }
        return $this->getProperty("SettingsBlockMyMeetingsAndFiles");
    }
    /**
     * @var bool
     */
    public function setSettingsBlockMyMeetingsAndFiles($value)
    {
        $this->setProperty("SettingsBlockMyMeetingsAndFiles", $value, true);
    }
    /**
     * @return bool
     */
    public function getSettingsBlockSessionResume()
    {
        if (!$this->isPropertyAvailable("SettingsBlockSessionResume")) {
            return null;
        }
        return $this->getProperty("SettingsBlockSessionResume");
    }
    /**
     * @var bool
     */
    public function setSettingsBlockSessionResume($value)
    {
        $this->setProperty("SettingsBlockSessionResume", $value, true);
    }
    /**
     * @return bool
     */
    public function getSettingsBlockSigninSuggestions()
    {
        if (!$this->isPropertyAvailable("SettingsBlockSigninSuggestions")) {
            return null;
        }
        return $this->getProperty("SettingsBlockSigninSuggestions");
    }
    /**
     * @var bool
     */
    public function setSettingsBlockSigninSuggestions($value)
    {
        $this->setProperty("SettingsBlockSigninSuggestions", $value, true);
    }
    /**
     * @return integer
     */
    public function getSettingsDefaultVolume()
    {
        if (!$this->isPropertyAvailable("SettingsDefaultVolume")) {
            return null;
        }
        return $this->getProperty("SettingsDefaultVolume");
    }
    /**
     * @var integer
     */
    public function setSettingsDefaultVolume($value)
    {
        $this->setProperty("SettingsDefaultVolume", $value, true);
    }
    /**
     * @return integer
     */
    public function getSettingsScreenTimeoutInMinutes()
    {
        if (!$this->isPropertyAvailable("SettingsScreenTimeoutInMinutes")) {
            return null;
        }
        return $this->getProperty("SettingsScreenTimeoutInMinutes");
    }
    /**
     * @var integer
     */
    public function setSettingsScreenTimeoutInMinutes($value)
    {
        $this->setProperty("SettingsScreenTimeoutInMinutes", $value, true);
    }
    /**
     * @return integer
     */
    public function getSettingsSessionTimeoutInMinutes()
    {
        if (!$this->isPropertyAvailable("SettingsSessionTimeoutInMinutes")) {
            return null;
        }
        return $this->getProperty("SettingsSessionTimeoutInMinutes");
    }
    /**
     * @var integer
     */
    public function setSettingsSessionTimeoutInMinutes($value)
    {
        $this->setProperty("SettingsSessionTimeoutInMinutes", $value, true);
    }
    /**
     * @return integer
     */
    public function getSettingsSleepTimeoutInMinutes()
    {
        if (!$this->isPropertyAvailable("SettingsSleepTimeoutInMinutes")) {
            return null;
        }
        return $this->getProperty("SettingsSleepTimeoutInMinutes");
    }
    /**
     * @var integer
     */
    public function setSettingsSleepTimeoutInMinutes($value)
    {
        $this->setProperty("SettingsSleepTimeoutInMinutes", $value, true);
    }
    /**
     * @return bool
     */
    public function getWelcomeScreenBlockAutomaticWakeUp()
    {
        if (!$this->isPropertyAvailable("WelcomeScreenBlockAutomaticWakeUp")) {
            return null;
        }
        return $this->getProperty("WelcomeScreenBlockAutomaticWakeUp");
    }
    /**
     * @var bool
     */
    public function setWelcomeScreenBlockAutomaticWakeUp($value)
    {
        $this->setProperty("WelcomeScreenBlockAutomaticWakeUp", $value, true);
    }
    /**
     * @return string
     */
    public function getWelcomeScreenBackgroundImageUrl()
    {
        if (!$this->isPropertyAvailable("WelcomeScreenBackgroundImageUrl")) {
            return null;
        }
        return $this->getProperty("WelcomeScreenBackgroundImageUrl");
    }
    /**
     * @var string
     */
    public function setWelcomeScreenBackgroundImageUrl($value)
    {
        $this->setProperty("WelcomeScreenBackgroundImageUrl", $value, true);
    }
}