<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:05:50+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValue;
class WorkbookIcon extends ClientValue
{
    /**
     * @var integer
     */
    public $Index;
    /**
     * @var string
     */
    public $Set;
}