<?php

/**
 * Generated by phpSPO model generator 2020-05-24T22:06:36+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientValueObject;
class WorkingHours extends ClientValueObject
{
    /**
     * @var TimeZoneBase
     */
    public $TimeZone;
}