<?php

/**
 * Generated by phpSPO model generator 2020-05-24T22:10:26+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientObject;
use Office365\Runtime\ResourcePath;
class WorkbookChart extends ClientObject
{
    /**
     * @return double
     */
    public function getHeight()
    {
        if (!$this->isPropertyAvailable("Height")) {
            return null;
        }
        return $this->getProperty("Height");
    }
    /**
     * @var double
     */
    public function setHeight($value)
    {
        $this->setProperty("Height", $value, true);
    }
    /**
     * @return double
     */
    public function getLeft()
    {
        if (!$this->isPropertyAvailable("Left")) {
            return null;
        }
        return $this->getProperty("Left");
    }
    /**
     * @var double
     */
    public function setLeft($value)
    {
        $this->setProperty("Left", $value, true);
    }
    /**
     * @return string
     */
    public function getName()
    {
        if (!$this->isPropertyAvailable("Name")) {
            return null;
        }
        return $this->getProperty("Name");
    }
    /**
     * @var string
     */
    public function setName($value)
    {
        $this->setProperty("Name", $value, true);
    }
    /**
     * @return double
     */
    public function getTop()
    {
        if (!$this->isPropertyAvailable("Top")) {
            return null;
        }
        return $this->getProperty("Top");
    }
    /**
     * @var double
     */
    public function setTop($value)
    {
        $this->setProperty("Top", $value, true);
    }
    /**
     * @return double
     */
    public function getWidth()
    {
        if (!$this->isPropertyAvailable("Width")) {
            return null;
        }
        return $this->getProperty("Width");
    }
    /**
     * @var double
     */
    public function setWidth($value)
    {
        $this->setProperty("Width", $value, true);
    }
}