<?php

/**
 * Generated by phpSPO model generator 2020-05-26T22:07:25+00:00 
 */
namespace Office365\Graph;

use Office365\Runtime\ClientObject;
use Office365\Runtime\ResourcePath;
class WorkbookFilter extends ClientObject
{
    /**
     * @return WorkbookFilterCriteria
     */
    public function getCriteria()
    {
        if (!$this->isPropertyAvailable("Criteria")) {
            return null;
        }
        return $this->getProperty("Criteria");
    }
    /**
     * @var WorkbookFilterCriteria
     */
    public function setCriteria($value)
    {
        $this->setProperty("Criteria", $value, true);
    }
}