<?php

/**
 * This file was generated by phpSPO model generator 2019-11-17T17:00:44+00:00 16.0.19506.12022
 */
namespace Office365\SharePoint;


/**
 * A utility 
 * class to retrieve App site context objects.
 */
class AppSiteContextUtility extends BaseEntity
{
}