<?php

/**
 * This file was generated by phpSPO model generator 2019-10-12T18:45:59+00:00 16.0.19402.12016
 */
namespace Office365\SharePoint;

use Office365\Runtime\ClientValue;

class AsyncReadOptions extends ClientValue
{
    /**
     * @var bool
     */
    public $IncludeDirectDescendantsOnly;
    /**
     * @var bool
     */
    public $IncludeExtendedMetadata;
    /**
     * @var bool
     */
    public $IncludeSecurity;
    /**
     * @var bool
     */
    public $IncludeVersions;
    /**
     * @var string
     */
    public $StartChangeToken;
}