<?php

/**
 * This file was generated by phpSPO model generator 2019-10-12T18:45:59+00:00 16.0.19402.12016
 */
namespace Office365\SharePoint;

use Office365\Runtime\ClientValue;
/**
 * Microsoft.SharePoint.Client.CopyJobProgress 
 * is not applicable.<251>
 */
class CopyJobProgress extends ClientValue
{
    /**
     * @var integer
     */
    public $JobState;
    /**
     * @var array
     */
    public $Logs;
}