<?php

/**
 * This file was generated by phpSPO model generator 2019-11-17T14:38:48+00:00 16.0.19506.12022
 */
namespace Office365\SharePoint;

use Office365\Runtime\ClientValue;

class CountByDate extends ClientValue
{
    /**
     * @var integer
     */
    public $count;
    /**
     * @var integer
     */
    public $date;
}