<?php

/**
 * This file was generated by phpSPO model generator 2019-10-12T18:42:56+00:00 16.0.19402.12016
 */
namespace Office365\SharePoint;

use Office365\Runtime\ClientValue;
/**
 * Migration 
 * options.<259>
 */
class EncryptionOption extends ClientValue
{
    /**
     * @var string
     */
    public $AES256CBCKey;
}