<?php

/**
 * This file was generated by phpSPO model generator 2020-04-23T09:31:03+00:00 16.0.20008.12009
 */
namespace Office365\SharePoint;

use Office365\Runtime\ClientObject;

class FavoriteLists extends ClientObject
{
}