<?php

/**
 * This file was generated by phpSPO model generator 2019-10-08T21:49:15+00:00 16.0.19325.12009 
*/
namespace Office365\SharePoint;

use Office365\Runtime\ClientValue;
class IngestionTaskKey extends ClientValue
{
    /** 
     * @var string  
     */
    public $IngestionTableAccountKey;
    /** 
     * @var string  
     */
    public $IngestionTableAccountName;
    /** 
     * @var string  
     */
    public $JobId;
    /** 
     * @var string  
     */
    public $TaskId;
    /** 
     * @var string  
     */
    public $TenantName;
}