<?php

/**
 * This file was generated by phpSPO model generator 2020-04-25T17:43:34+00:00 16.0.20008.12009
 */
namespace Office365\SharePoint;

use Office365\Runtime\ClientValue;
class KeyValue extends ClientValue
{
    /**
     * @var string
     */
    public $Key;
    /**
     * @var string
     */
    public $Value;
    /**
     * @var string
     */
    public $ValueType;
}