<?php

/**
 * This file was generated by phpSPO model generator 2019-10-26T18:35:54+00:00 16.0.19416.12016
 */
namespace Office365\SharePoint;

use Office365\Runtime\ClientValueCollection;

class ListDataValidationFailureCollection extends ClientValueCollection
{

}