<?php

/**
 * This file was generated by phpSPO model generator 2019-10-08T21:36:37+00:00 16.0.19325.12009
*/
namespace Office365\SharePoint;

use Office365\Runtime\ClientValue;
class PortalAndOrgNewsSiteReference extends ClientValue
{
    /** 
     * @var string  
     */
    public $SiteId;
    /** 
     * @var string  
     */
    public $WebId;
}