<?php

/**
 * This file was generated by phpSPO model generator 2019-10-12T18:54:53+00:00 16.0.19402.12016
 */
namespace Office365\SharePoint;

use Office365\Runtime\ClientValue;
/**
 * Microsoft.SharePoint.Client.ProvisionedMigrationContainersInfo 
 * is not applicable.<267>
 */
class ProvisionedMigrationContainersInfo extends ClientValue
{
    /**
     * @var string
     */
    public $DataContainerUri;
    /**
     * @var string
     */
    public $EncryptionKey;
    /**
     * @var string
     */
    public $MetadataContainerUri;
}