<?php

/**
 * This file was generated by phpSPO model generator 2019-10-08T21:51:16+00:00 16.0.19325.12009
*/
namespace Office365\SharePoint;

use Office365\Runtime\ClientValue;
class RelatedItem extends ClientValue
{
    /** 
     * @var string  
     */
    public $IconUrl;
    /** 
     * @var integer  
     */
    public $ItemId;
    /** 
     * @var string  
     */
    public $ListId;
    /** 
     * @var string  
     */
    public $Title;
    /** 
     * @var string  
     */
    public $Url;
    /** 
     * @var string  
     */
    public $WebId;
}