<?php

/**
 * This file was generated by phpSPO model generator 2022-04-22T09:37:05+03:00 16.0.22406.12004
 */
namespace Office365\SharePoint;

use Office365\Runtime\ClientValue;
class SensitivityLabelInfo extends ClientValue
{
    /**
     * @var string
     */
    public $DisplayName;
    /**
     * @var string
     */
    public $Id;
    /**
     * @var string
     */
    public $MembersCanShare;
}