<?php

/**
 * This file was generated by phpSPO model generator 2019-11-17T17:00:44+00:00 16.0.19506.12022
 */
namespace Office365\SharePoint;

use Office365\Runtime\ClientObject;

/**
 * Provides 
 * methods for obtaining protocol server properties that correspond to different Web 
 * application zones.<177>
 */
class ServerSettings extends ClientObject
{
}