<?php

/**
 * This file was generated by phpSPO model generator 2019-12-21T23:07:44+00:00 16.0.19520.12047
 */
namespace Office365\SharePoint;

use Office365\Runtime\ClientValue;

class SPImageItem extends ClientValue
{
    /**
     * @var string
     */
    public $Name;
    /**
     * @var string
     */
    public $ServerRelativeUrl;
    /**
     * @var string
     */
    public $UniqueId;
}