<?php

/**
 * This file was generated by phpSPO model generator 2019-10-12T19:07:48+00:00 16.0.19402.12016
 */
namespace Office365\SharePoint;

use Office365\Runtime\ClientValue;

class TranslationStatusCreationRequest extends ClientValue
{
    /**
     * @var array
     */
    public $LanguageCodes;
}