<?php

/**
 * This file was generated by phpSPO model generator 2019-11-17T15:06:51+00:00 16.0.19506.12022
 */
namespace Office365\SharePoint;

use Office365\Runtime\ClientObject;

/**
 * An object 
 * representing user-defined localizable resources.
 */
class UserResource extends ClientObject
{
}