<?php

/**
 * This file was generated by phpSPO model generator 2019-10-12T19:34:55+00:00 16.0.19402.12016
 */
namespace Office365\SharePoint\Directory\Provider;

use Office365\Runtime\ClientValue;

class AlternateIdData extends ClientValue
{
    /**
     * @var string
     */
    public $Email;
    /**
     * @var integer
     */
    public $IdentifyingProperty;
    /**
     * @var string
     */
    public $UserPrincipalName;
}