<?php

/**
 * This file was generated by phpSPO model generator 2019-10-12T19:41:09+00:00 16.0.19402.12016
 */
namespace Office365\SharePoint\UserProfiles;

use Office365\Runtime\ClientValue;

class CrossGeoSyncUserProperty extends ClientValue
{
    /**
     * @var string
     */
    public $DsGuid;
    /**
     * @var bool
     */
    public $IsMultivalue;
    /**
     * @var integer
     */
    public $Privacy;
    /**
     * @var integer
     */
    public $PropertyId;
    /**
     * @var string
     */
    public $PropertyVal;
    /**
     * @var string
     */
    public $SecondaryVal;
}