<?php

/**
 * This file was generated by phpSPO model generator 2019-10-12T19:41:09+00:00 16.0.19402.12016
 */
namespace Office365\SharePoint\UserProfiles;

use Office365\Runtime\ClientValue;

class FollowedItem extends ClientValue
{
    /**
     * @var array
     */
    public $Data;
    /**
     * @var string
     */
    public $FileType;
    /**
     * @var string
     */
    public $FileTypeProgid;
    /**
     * @var string
     */
    public $Flags;
    /**
     * @var string
     */
    public $GroupId;
    /**
     * @var bool
     */
    public $HasFeed;
    /**
     * @var bool
     */
    public $Hidden;
    /**
     * @var string
     */
    public $IconUrl;
    /**
     * @var integer
     */
    public $ItemId;
    /**
     * @var integer
     */
    public $ItemType;
    /**
     * @var string
     */
    public $ListId;
    /**
     * @var string
     */
    public $ParentUrl;
    /**
     * @var integer
     */
    public $Pinned;
    /**
     * @var string
     */
    public $ServerUrlProgid;
    /**
     * @var string
     */
    public $SiteId;
    /**
     * @var integer
     */
    public $Subtype;
    /**
     * @var string
     */
    public $Title;
    /**
     * @var string
     */
    public $UniqueId;
    /**
     * @var string
     */
    public $Url;
    /**
     * @var string
     */
    public $WebId;
}