<?php

/**
 * This file was generated by phpSPO model generator 2019-11-17T18:22:48+00:00 16.0.19506.12022
 */
namespace Office365\SharePoint\UserProfiles;


use Office365\Runtime\ResourcePath;
use Office365\SharePoint\BaseEntity;
use Office365\SharePoint\BaseEntityCollection;


class HashTagCollection extends BaseEntity
{
    /**
     * @return HashTagCollection
     */
    public function getItems()
    {
        return $this->getProperty("Items",
            new BaseEntityCollection($this->getContext(),
                new ResourcePath("items",$this->resourcePath), HashTag::class));
    }

}