<?php

/**
 * This file was generated by phpSPO model generator 2020-04-25T20:49:12+00:00 16.0.20008.12009
 */
namespace Office365\OutlookServices;

use Office365\Runtime\ResourcePath;

/**
 * A group of calendars.
 */
class CalendarGroup extends OutlookEntity
{
    /**
     * @var string
     */
    public $Name;
    /**
     * @var string
     */
    public $ClassId;
    /**
     * @var string
     */
    public $ChangeKey;
    /**
     * @return CalendarCollection
     */
    public function getCalendars()
    {
        if (!$this->isPropertyAvailable("Calendars")) {
            $this->setProperty("Calendars", new CalendarCollection($this->getContext(),
                new ResourcePath("Calendars", $this->getResourcePath())));
        }
        return $this->getProperty("Calendars");
    }
}