<?php

/**
 * Generated by phpSPO model generator 2020-05-24T22:03:02+00:00 
 */
namespace Office365\OutlookServices;

use Office365\Graph\Entity;
use Office365\Runtime\ClientObject;
/**
 * Represents the Outlook services available to a user.
 */
class OutlookUser extends Entity
{
}