<?php

/**
 * This file was generated by phpSPO model generator 2019-10-12T20:10:10+00:00 16.0.19402.12016
 */
namespace Office365\SharePoint\Utilities;

use Office365\Runtime\ClientValue;
/**
 * Microsoft.SharePoint.Client.Utilities.ThemingOptions 
 * is not applicable.<277>
 */
class ThemingOptions extends ClientValue
{
    /**
     * @var bool
     */
    public $hideDefaultThemes;
    /**
     * @var array
     */
    public $themePreviews;
}