<?php

/**
 * This file was generated by phpSPO model generator 2019-11-17T18:33:00+00:00 16.0.19506.12022
 */
namespace Office365\SharePoint\Utilities;

use Office365\Runtime\ClientObject;


class ThemeManager extends ClientObject
{
}