<?php

/**
 * This file was generated by phpSPO model generator 2019-10-12T19:41:09+00:00 16.0.19402.12016
 */
namespace Office365\SharePoint\Publishing;

use Office365\Runtime\ClientValue;

class AcronymInformation extends ClientValue
{
    /**
     * @var string
     */
    public $Acronym;
    /**
     * @var string
     */
    public $Color;
    /**
     * @var integer
     */
    public $Lcid;
    /**
     * @var string
     */
    public $Text;
}