<?php

/**
 * This file was generated by phpSPO model generator 2020-08-19T18:22:34+00:00 16.0.20405.12008
 */
namespace Office365\SharePoint\Publishing;

use Office365\Runtime\ClientValue;
class BoostFieldsData extends ClientValue
{
    /**
     * @var bool
     */
    public $BoostUntilSeen;
    /**
     * @var string
     */
    public $Expiry;
    /**
     * @var integer
     */
    public $Impressions;
    /**
     * @var integer
     */
    public $BoostOrderType;
    /**
     * @var integer
     */
    public $NextItemId;
    /**
     * @var integer
     */
    public $NextItemVersion;
    /**
     * @var integer
     */
    public $PreviousItemId;
    /**
     * @var integer
     */
    public $PreviousItemVersion;
}