<?php

/**
 * This file was generated by phpSPO model generator 2021-05-05T14:47:20+00:00 16.0.21221.12006
 */
namespace Office365\SharePoint\Publishing;


use Office365\SharePoint\BaseEntity;

class FeedVideoPage extends BaseEntity
{
    /**
     * @return integer
     */
    public function getVideoDuration()
    {
        return $this->getProperty("VideoDuration");
    }

    /**
     * @param $value
     * @return self
     */
    public function setVideoDuration($value)
    {
        return $this->setProperty("VideoDuration", $value, true);
    }
}