<?php

/**
 * This file was generated by phpSPO model generator 2020-04-23T18:46:51+00:00 16.0.20008.12009
 */
namespace Office365\SharePoint\Publishing;

use Office365\Runtime\ClientObject;

class PageDiagnosticsController extends ClientObject
{
}