<?php

/**
 * This file was generated by phpSPO model generator 2021-03-12T16:05:00+00:00 16.0.21103.12002
 */
namespace Office365\SharePoint\Publishing;

use Office365\Runtime\ClientValue;
class SitePageFieldsData extends ClientValue
{
    /**
     * @var array
     */
    public $AuthorByline;
    /**
     * @var string
     */
    public $BannerImageUrl;
    /**
     * @var string
     */
    public $CanvasContent1;
    /**
     * @var string
     */
    public $CanvasJson1;
    /**
     * @var string
     */
    public $Description;
    /**
     * @var string
     */
    public $LayoutWebpartsContent;
    /**
     * @var string
     */
    public $Modified;
    /**
     * @var string
     */
    public $Title;
    /**
     * @var string
     */
    public $TopicHeader;
    /**
     * @var string
     */
    public $PublishStartDate;
    /**
     * @var string
     */
    public $Categories;
}