<?php

/**
 * This file was generated by phpSPO model generator 2019-11-16T20:25:28+00:00 16.0.19506.12022
 */
namespace Office365\SharePoint\Publishing;

use Office365\Runtime\ClientValue;

class SitePageFieldsData extends ClientValue
{
    /**
     * @var array
     */
    public $AuthorByline;
    /**
     * @var string
     */
    public $BannerImageUrl;
    /**
     * @var string
     */
    public $CanvasContent1;
    /**
     * @var string
     */
    public $CanvasJson1;
    /**
     * @var string
     */
    public $Description;
    /**
     * @var string
     */
    public $LayoutWebpartsContent;
    /**
     * @var string
     */
    public $Modified;
    /**
     * @var string
     */
    public $Title;
    /**
     * @var string
     */
    public $TopicHeader;
    /**
     * @var string
     */
    public $PublishStartDate;
}