<?php

/**
 * Generated by phpSPO model generator 2020-05-29T07:19:37+00:00 
 */
namespace Office365\Teams;

use Office365\Runtime\ClientValue;
class ShiftActivity extends ClientValue
{
    /**
     * @var bool
     */
    public $IsPaid;
    /**
     * @var string
     */
    public $Code;
    /**
     * @var string
     */
    public $DisplayName;
}