<?php

/**
 * Generated by phpSPO model generator 2020-05-29T07:19:37+00:00 
 */
namespace Office365\Teams;

use Office365\Entity;

/**
 * Represents a user's availability to be assigned shifts in the [schedule](schedule.md).
 */
class ShiftPreferences extends Entity
{
}