<?php

/**
 * This file was generated by phpSPO model generator 2019-10-12T20:07:53+00:00 16.0.19402.12016
 */
namespace Office365\SharePoint\UI\ApplicationPages;

use Office365\Runtime\ClientValue;

class PeoplePickerQuerySettings extends ClientValue
{
    /**
     * @var bool
     */
    public $ExcludeAllUsersOnTenantClaim;
    /**
     * @var bool
     */
    public $IsSharing;
}