<?php

/**
 * This file was generated by phpSPO model generator 2019-11-17T17:00:44+00:00 16.0.19506.12022
 */
namespace Office365\SharePoint\Social;

use Office365\SharePoint\BaseEntity;


class SocialRestFeed extends BaseEntity
{
    /**
     * @return SocialFeed
     */
    public function getSocialFeed()
    {
        if (!$this->isPropertyAvailable("SocialFeed")) {
            return null;
        }
        return $this->getProperty("SocialFeed");
    }

    /**
     *
     * @return SocialRestFeed
     * @var SocialFeed
     */
    public function setSocialFeed($value)
    {
        $this->setProperty("SocialFeed", $value, true);
        return $this;
    }
}
