<?php

/**
 * This file was generated by phpSPO model generator 2020-10-07T15:32:14+00:00 16.0.20523.12005
 */
namespace Office365\SharePoint\ComplianceFoundation\Models;

use Office365\Runtime\ClientValue;
class RetentionWorkItemInput extends ClientValue
{
    /**
     * @var string
     */
    public $SignalsEndTimeStamp;
    /**
     * @var string
     */
    public $SignalsStartTimeStamp;
    /**
     * @var string
     */
    public $SignalsStorageName;
}